services:
  sample-java-server:
    container_name: sample-java-server
    build:
      context: .
      args:
        OTEL_ENDPOINT: "http://apm-otel-collector:4317"
    depends_on:
      - sample-java-database
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: "sample-java-database"
      DATABASE_PORT: "5432"
      OTEL_ENDPOINT: "http://apm-otel-collector:4317"
    networks:
      - default
      - otel-java

  sample-java-database:
    container_name: sample-java-database
    image: postgres:17
    volumes:
      - ./volume/database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "sample"
      POSTGRES_USER: "sample"
      POSTGRES_PASSWORD: "sample"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sample -d sample" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default

networks:
  default:
  otel-java:
    name: otel-java