apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actions-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 20Gi