import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: "flex", height: "100vh" }}>
          <aside
            style={{
              width: "250px",
              borderRight: "1px solid #eaeaea",
              padding: "20px",
            }}
          >
            <h1 style={{ marginBottom: "20px" }}>Next.js Cache Test</h1>
            <nav>
              <ul style={{ listStyle: "none", padding: 0 }}>
                <li style={{ marginBottom: "10px" }}>
                  <Link href="/image-rendering">Image Rendering Test</Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                  <Link href="/ssr">SSR Test</Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                  <Link href="/csr">CSR Test</Link>
                </li>
              </ul>
            </nav>
          </aside>
          <main style={{ flex: 1, padding: "20px" }}>{children}</main>
        </div>
      </body>
    </html>
  );
}
