services:
  # Jaeger
  jaeger:
    container_name: apm-jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "14250:14250" # gRPC
      - "4317:4317" # ✅ OTLP-gRPC를 위한 포트 추가
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - default
      - otel-java
      - otel-python

  # OpenTelemetry Collector
  otel-collector:
    container_name: apm-otel-collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./volume/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    # ports:
    #   - "4317:4317"   # OTLP gRPC receiver
    #   - "4318:4318"   # OTLP http receiver
    #   - "8888:8888"   # Prometheus metrics exposed by the collector
    #   - "8889:8889"   # Prometheus exporter metrics
    #   - "13133:13133" # health_check extension
    depends_on:
      - jaeger
    networks:
      - default
      - otel-java
      - otel-python

networks:
  default:
  otel-java:
    external: true
    name: otel-java
  otel-python:
    external: true
    name: otel-python
