services:
  runner1:
    image: myoung34/github-runner
    container_name: github_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUNNER_NAME=docker-runner
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REPO_URL=https://github.com/moseoh/build-test
      - RUNNER_SCOPE=repo
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4g
        reservations:
          cpus: "1"
          memory: 1g
