---
- name: Initialize Snapshot
  hosts: all
  become: true
  tasks:
    # Step : Timeshift 설치 여부 확인
    - name: Check Timeshift Installation
      block:
        - name: Check Timeshift Installation
          command: which timeshift
          register: timeshift_check
          changed_when: false
          failed_when: false
          ignore_errors: true

        - name: Set Timeshift installation status
          set_fact:
            installed_timeshift: "{{ timeshift_check.rc == 0 }}"

    - name: Install Timeshift if not installed
      when: not installed_timeshift
      block:
        - name: Update APT package cache
          apt:
            update_cache: yes

        - name: Install Timeshift package
          apt:
            name: timeshift
            state: present

        - name: Verify Timeshift installation
          command: which timeshift
          register: verify_timeshift
          changed_when: false
          failed_when: verify_timeshift.rc != 0
          ignore_errors: false

    # Step : 기존 스냅샷 확인 및 상태 설정
    - name: Check Existing Snapshots
      block:
        - name: Check existing snapshots
          command: timeshift --list-snapshots
          register: snapshot_list
          changed_when: false
          failed_when: false

        - name: Set snapshot existence status
          set_fact:
            exist_snapshots: "{{ 'No snapshots found' not in snapshot_list.stdout }}"

        - name: Show snapshot status
          debug:
            msg: "{{ 'Snapshots already exist - skipping initialization' if exist_snapshots else 'No snapshots found - proceeding with initialization' }}"

    # Step : 스냅샷이 없는 경우에만 초기화 진행
    - name: Initialize timeshift when no snapshots exist
      when: not exist_snapshots
      block:
        # Step : timeshift-backup 디바이스의 UUID 찾기
        - name: Find UUID of timeshift-backup volume
          command: blkid -s UUID -o value /dev/ubuntu-vg/timeshift-backup
          register: timeshift_backup_uuid
          changed_when: false

        - name: Debug UUID of timeshift-backup
          debug:
            msg: "UUID of timeshift-backup: {{ timeshift_backup_uuid.stdout.strip() }}"

        # Step : Timeshift 설정 파일 생성
        - name: Create or Update Timeshift configuration file
          copy:
            dest: /etc/timeshift/timeshift.json
            content: |
              {
                "backup_device_uuid" : "{{ timeshift_backup_uuid.stdout.strip() }}",
                "parent_device_uuid" : "",
                "do_first_run" : "false",
                "btrfs_mode" : "false",
                "include_btrfs_home_for_backup" : "false",
                "include_btrfs_home_for_restore" : "false",
                "stop_cron_emails" : "true",
                "schedule_monthly" : "false",
                "schedule_weekly" : "false",
                "schedule_daily" : "false",
                "schedule_hourly" : "false",
                "schedule_boot" : "false",
                "count_monthly" : "1",
                "count_weekly" : "1",
                "count_daily" : "1",
                "count_hourly" : "1",
                "count_boot" : "1",
                "date_format" : "%Y-%m-%d %H:%M:%S",
                "exclude" : [],
                "exclude-apps" : []
              }
            owner: root
            group: root
            mode: "0644"

        # Step : 초기 Timeshift 스냅샷 생성
        - name: Create initial Timeshift snapshot
          command: timeshift --create --comments "Initial clean backup"
          register: snapshot_status

        # 결과 출력
        - name: Display snapshot creation status
          debug:
            var: snapshot_status.stdout
