services:
  sample-python-server:
    container_name: sample-python-server
    build:
      context: .
    ports:
      - "8002:8000"
    environment:
      DATABASE_USER: "sample"
      DATABASE_PASSWORD: "sample"
      DATABASE_HOST: "sample-python-database"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "sample"
      OTEL_ENDPOINT: "http://apm-otel-collector:4317"
    depends_on:
      sample-python-database:
        condition: service_healthy
    networks:
      - default
      - otel-python

  sample-python-database:
    container_name: sample-python-database
    image: postgres:17
    volumes:
      - ./volume/database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "sample"
      POSTGRES_USER: "sample"
      POSTGRES_PASSWORD: "sample"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sample -d sample"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:
  otel-python:
    name: otel-python
