services:
  go-database:
    image: postgres:17
    container_name: go-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: go-database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - go-database
