services:
  nfs-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfs-server
    privileged: true
    restart: unless-stopped
    volumes:
      - nfs_data:/nfs_share
    networks:
      - nfs-network
    healthcheck:
      test: ["CMD", "showmount", "-e", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3

  nfs-client1:
    image: alpine:latest
    container_name: nfs-client1
    privileged: true
    restart: unless-stopped
    depends_on:
      nfs-server:
        condition: service_healthy
    command: >
      sh -c "
        apk add --no-cache nfs-utils &&
        mkdir -p /mnt/nfs &&
        echo 'Waiting for NFS server...' &&
        sleep 5 &&
        mount -t nfs -o nfsvers=3,nolock nfs-server:/nfs_share /mnt/nfs &&
        echo 'NFS mounted successfully on client1' &&
        tail -f /dev/null
      "
    networks:
      - nfs-network

  nfs-client2:
    image: alpine:latest
    container_name: nfs-client2
    privileged: true
    restart: unless-stopped
    depends_on:
      nfs-server:
        condition: service_healthy
    command: >
      sh -c "
        apk add --no-cache nfs-utils &&
        mkdir -p /mnt/nfs &&
        echo 'Waiting for NFS server...' &&
        sleep 5 &&
        mount -t nfs -o nfsvers=3,nolock nfs-server:/nfs_share /mnt/nfs &&
        echo 'NFS mounted successfully on client2' &&
        tail -f /dev/null
      "
    networks:
      - nfs-network

volumes:
  nfs_data:
    driver: local

networks:
  nfs-network:
    driver: bridge