services:
  grafana:
    image: grafana/grafana:latest
    networks:
      - k6
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
      - INFLUXDB_MAX_BODY_SIZE=0
    volumes:
      - influxdb_data:/var/lib/influxdb

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565" # k6의 기본 API 포트
    environment:
      - K6_INFLUXDB_PUSH_INTERVAL=10s
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - K6_BATCH_SIZE=200
      - K6_FLUSH_INTERVAL=5s
    volumes:
      - ./scripts:/scripts

networks:
  k6:
    name: k6

volumes:
  influxdb_data:
  grafana_data:
