services:
  docker-runner-1:
    image: myoung34/github-runner:latest
    container_name: docker-runner-1
    restart: unless-stopped
    environment:
      - RUNNER_NAME=docker-runner-1
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_REPOSITORY_URL=${RUNNER_REPOSITORY_URL}
      - RUNNER_WORK_DIRECTORY=${RUNNER_WORK_DIRECTORY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  docker-runner-2:
    image: myoung34/github-runner:latest
    container_name: docker-runner-2
    restart: unless-stopped
    environment:
      - RUNNER_NAME=docker-runner-2
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_REPOSITORY_URL=${RUNNER_REPOSITORY_URL}
      - RUNNER_WORK_DIRECTORY=${RUNNER_WORK_DIRECTORY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
